# Kaggle link
https://www.kaggle.com/code/mirajverisk/kaggle-pandas-full

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/mirajverisk/pandas-datas/student_data_english.csv
/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/excel_df.xlsx
/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/new_data.csv
/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/example.xlsx


**python Pandas** is a library which helps to create the following Data Structures

* Series - 1D array of data
* DataFrame - 2D array of data



**A) Series** - Series is the 1D Data Structure <br>
*Different ways of Creating Series in pandas*
* Series With Array
* Series With Lists
* Series With Dictionary

In [2]:
import pandas as pd

#Creating Series with list
l=[1,2,3,4,5]
s=pd.Series(l)
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
#we can also change the index of series by
l=[1,2,3,4,5]
s=pd.Series(l,index=['a','b','c','d','e'])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [4]:
#Creating Series with Array
import numpy as np
a=np.array([80,20,78])
s=pd.Series(a)
s

0    80
1    20
2    78
dtype: int64

In [6]:
#Creating Series with Dictionary
d={'name':'miraj','roll':10,'age':15}
s=pd.Series(d)
s

name    miraj
roll       10
age        15
dtype: object

# Attributes for Series

- **`series.index`** – Returns all index values of the Series.

- **`series.array`** – Returns all elements as a Pandas array.

- **`series.dtype`** – Returns the data type of the elements in the Series.

- **`series.values`** – Returns the elements of the Series as a NumPy array.

- **`series.shape`** – Returns the shape of the Series. Since a Series is 1-dimensional, it returns only the number of elements.
  ```python
  (n,)
  ```

- **`series.ndim`** – Returns the number of dimensions of the Series.

- **`series.size`** – Returns the total number of elements present in the Series.

- **`series.empty`** – Returns:
  - `True` if the Series is empty.
  - `False` if the Series is not empty.

- **`series.at`** – Returns a single element from the Series using a label-based index.

- **`series.iat`** – Returns a single element from the Series using an integer-based index.

- **`series.loc`** – Label-based indexing and slicing. Similar to `DataFrame.loc`.

- **`series.iloc`** – Integer-based indexing and slicing. Similar to `DataFrame.iloc`.
  - The last index is **exclusive** when slicing.

In [7]:
s= pd.Series(['miraj','aman','apil','sabal'], index=['a','b','c','d'])
s

a    miraj
b     aman
c     apil
d    sabal
dtype: object

In [8]:
#using index attributes (returns all index values)
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [11]:
#using array attributes (returns all data in pandas array)
s.array

<NumpyExtensionArray>
['miraj', 'aman', 'apil', 'sabal']
Length: 4, dtype: object

In [12]:
#using dtype attributes gives what is the data types of elements of this series
s.dtype

dtype('O')

In [13]:
#using values attributes (returns values of series in numpy array)
s.values

array(['miraj', 'aman', 'apil', 'sabal'], dtype=object)

In [14]:
#using shape attributes (for series shape 4 represents the 4 rows )
#for series s.shape also help us to find the numbers of elements in the series like s.size
s.shape

(4,)

In [15]:
#using shape attributes (returns the no of dimension of the series)
s.ndim

1

In [16]:
#using size attributes gives the total number of elements in the series
s.size

4

In [17]:
#using empty attributes gives boolean values (if series is empty then True and if series is not empty then False)
s.empty

False

In [15]:
s

a    miraj
b     aman
c     apil
d    sabal
dtype: object

In [18]:
s.at['a'] # 'a' label ma vako value dinxa series bata
#s['a']

'miraj'

In [19]:
s.iat[3]# '3' index ma vako value dinxa series bata

'sabal'

# Mathematical Operations in series

In [22]:
import pandas as pd
s1=pd.Series([1,2,3])
s2=pd.Series([2,3,4])

In [23]:
#add
s1+s2
#s1.add(s2)

0    3
1    5
2    7
dtype: int64

In [24]:
#substract
s1-s2

0   -1
1   -1
2   -1
dtype: int64

In [25]:
#multiply
s1*s2

0     2
1     6
2    12
dtype: int64

In [26]:
#division
s1/s2

0    0.500000
1    0.666667
2    0.750000
dtype: float64

In [27]:
#power
s1**s2

0     1
1     8
2    81
dtype: int64

In [28]:
#less than
s1<s2

0    True
1    True
2    True
dtype: bool

In [29]:
#greater than
s1>s2

0    False
1    False
2    False
dtype: bool

In [30]:
#equalto
s1==s2

0    False
1    False
2    False
dtype: bool

# Getting value from the series

In [27]:
import pandas as pd
s=pd.Series([1,3,4,6])
s

0    1
1    3
2    4
3    6
dtype: int64

In [32]:
#getting index 3 value
print(s[3])

sabal

/tmp/ipykernel_58/2327264386.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[3])

In [33]:
#getting index 1 and 2 element
s[1:3]

b    aman
c    apil
dtype: object

In [34]:
#we can also set index like this in series
s.index=['a','b','c','d']
s

a    miraj
b     aman
c     apil
d    sabal
dtype: object

In [35]:
print(s['d'])

sabal


**B) DataFrame -**
Data Frame is the 2D Data Structure (tabluar form) <br>
Different ways of Creating Data Frame in pandas

* By reading data from Excel File
* By reading data from CSV File (comma seperated values)
* BY using Dictionary

In [36]:
#making data frame by reading excel
df=pd.read_excel(r"/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/excel_df.xlsx")
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [37]:
# making data frame by reading csv
df=pd.read_csv(r"/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/new_data.csv")
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [38]:
# making data frame by using dictionary
dict = {'name':['miraj','sabal','sarita','rashmi','sabnam'],
'roll':[1,2,3,4,5] ,'age':[13,34,32,54,32] }
df=pd.DataFrame(dict)
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

# Attributes for Data Frame



- **`df.T`** – Transposes the DataFrame (**rows become columns and columns become rows**).

- **`df.at[1, 'age']`** – Returns a **single element** from the DataFrame. It is **label-based** like `loc`.
  - No slicing allowed.
  - Returns only one element.

- **`df.iat[1, 2]`** – Returns a **single element** from the DataFrame. It is **index-based** like `iloc`.
  - No slicing allowed.
  - Returns only one element.

- **`df.axes`** – Returns the **row index names** and **column names**.

- **`df.index`** – Returns only the **row index names**.

- **`df.columns`** – Returns only the **column names**.

- **`df.empty`** – Returns a Boolean value:
  - `True` if the DataFrame is empty.
  - `False` if the DataFrame is not empty.

- **`df.ndim`** – Returns the **number of dimensions** of the DataFrame.

- **`df.shape`** – Returns the shape of the DataFrame as:
  ```python
  (number_of_rows, number_of_columns)
  ```

- **`df.size`** – Returns the **total number of elements** in the DataFrame.

- **`df.values`** – Converts the DataFrame into a **NumPy array**.

In [39]:
df #original dataframe

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [40]:
df.T #transpose

          0      1       2       3       4
name  miraj  sabal  sarita  rashmi  sabnam
roll      1      2       3       4       5
age      13     34      32      54      32

In [37]:
df #original dataframe

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [41]:
'''Similar to loc, both need label based lookups.
Use at if you only need to get or set a single value in a DataFrame or Series.'''

print(df.at[1,'age'])

34

In [42]:
df #original dataframe

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [43]:
df.index #gives the row index of the dataframe
df.index=['a','b','c','d','e']#we can also change index like this
df

     name  roll  age
a   miraj     1   13
b   sabal     2   34
c  sarita     3   32
d  rashmi     4   54
e  sabnam     5   32

In [44]:
df.axes # gives columns row names and columns anme
#df.axes[0]# row names
#df.axes[1]# columns names

[Index(['a', 'b', 'c', 'd', 'e'], dtype='object'),
 Index(['name', 'roll', 'age'], dtype='object')]

In [45]:
df #original dataframe

     name  roll  age
a   miraj     1   13
b   sabal     2   34
c  sarita     3   32
d  rashmi     4   54
e  sabnam     5   32

In [46]:
df.columns #gives coulmns names

Index(['name', 'roll', 'age'], dtype='object')

In [47]:
df.dtypes #Return what types of data is stoted by each columns in data frame

name    object
roll     int64
age      int64
dtype: object

In [48]:
df.ndim #It returns the dimension of the dataframe.

2

In [49]:
df.shape # It returns the number of rows and number of columns (nrows x ncolumns).

(5, 3)

In [50]:
df.size # gives the number of elements in the data frame

15

In [51]:
df #original dataframe

     name  roll  age
a   miraj     1   13
b   sabal     2   34
c  sarita     3   32
d  rashmi     4   54
e  sabnam     5   32

In [55]:
df.values #converts numpy dataframe into numpy array !!!

array([['miraj', 1, 13],
       ['sabal', 2, 34],
       ['sarita', 3, 32],
       ['rashmi', 4, 54],
       ['sabnam', 5, 32]], dtype=object)

# Important Methods() for DataFrame

- **`value_counts()`** – Returns how many times each unique value is repeated in a Series.
  ```python
  df['column'].value_counts()
  ```

- **`to_dict()`** – Converts a Series or DataFrame into a Python dictionary.

- **`sort_index()`** – Sorts a Series or DataFrame by its index in ascending order.

- **`sort_values()`** – Sorts a Series or DataFrame by its values in ascending order.

- **`set_index()`** – Sets an existing column as the index of a DataFrame.

- **`reset_index()`** – Resets the index of a DataFrame and converts the index into a regular column. Creates a new DataFrame with a default index.

- **`replace()`** – Replaces specified values in a Series or DataFrame with other values.

- **`rename()`** – Renames row index labels or column labels of a Series or DataFrame.

- **`query()`** – Filters a DataFrame using a Boolean expression and returns a new DataFrame containing the matching rows.

- **`notna()`** – Returns `True` for non-null values and `False` for null values.

- **`nsmallest()`** – Returns the *n* smallest values from a Series or DataFrame.

- **`nlargest()`** – Returns the *n* largest values from a Series or DataFrame.

- **`nunique()`** – Counts the number of unique values present in a column.

- **`info()`** – Provides a concise summary of a DataFrame, including data types, non-null values, and memory usage.

- **`describe()`** – Generates descriptive statistics of a DataFrame, including count, mean, standard deviation, minimum, maximum, and quartile values.

- **`count()`** – Counts the number of non-null values in each column of a DataFrame.

- **`copy()`** – Creates a deep copy of a Series or DataFrame.

In [57]:
df

     name  roll  age
a   miraj     1   13
b   sabal     2   34
c  sarita     3   32
d  rashmi     4   54
e  sabnam     5   32

In [58]:
df['age'].value_counts() # Count the occurrences of each unique item

age
32    2
13    1
34    1
54    1
Name: count, dtype: int64

In [59]:
# converts the dataframe into dictionary
df.to_dict()

{'name': {'a': 'miraj',
  'b': 'sabal',
  'c': 'sarita',
  'd': 'rashmi',
  'e': 'sabnam'},
 'roll': {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5},
 'age': {'a': 13, 'b': 34, 'c': 32, 'd': 54, 'e': 32}}

In [62]:
# we can also convert data frame into jason
df.to_json('new_data.json')

In [63]:
# reading from json file
df=pd.read_json('new_data.json')
df

     name  roll  age
a   miraj     1   13
b   sabal     2   34
c  sarita     3   32
d  rashmi     4   54
e  sabnam     5   32

In [64]:
df.index=['b','a','g','c','d']
#sorting the items on the basis of index in descending way
df.sort_index(ascending = False)

     name  roll  age
g  sarita     3   32
d  sabnam     5   32
c  rashmi     4   54
b   miraj     1   13
a   sabal     2   34

In [67]:
#setting the existing column to index
df.set_index('roll')

        name  age
roll
1      miraj   13
2      sabal   34
3     sarita   32
4     rashmi   54
5     sabnam   32

In [69]:
# reset of index to default one
df.reset_index()

  index    name  roll  age
0     b   miraj     1   13
1     a   sabal     2   34
2     g  sarita     3   32
3     c  rashmi     4   54
4     d  sabnam     5   32

In [70]:
df.reset_index(drop=True) #if we dont want extra index in colum we can do df.reset_index(drop=True)

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [71]:
# Dataframe whhich consists the nan values

data = {'Name': ['John', 'Emma', np.nan],
'Age': [25, np.nan, 30],
'Height': [175, 162, np.nan]}
df = pd.DataFrame(data)
df

   Name   Age  Height
0  John  25.0   175.0
1  Emma   NaN   162.0
2   NaN  30.0     NaN

In [59]:
#replacing nan values with None
df.replace(np.nan, None, inplace=True)
df

   Name   Age Height
0  John  25.0  175.0
1  Emma  None  162.0
2  None  30.0   None

In [74]:
#replacing Emma with Miraj
df.replace('Emma','Miraj',inplace=True)
df

    Name   Age Height
0   John  25.0  175.0
1  Miraj  None  162.0
2   None  30.0   None

In [75]:
# Renaming column labels and row labels
col_corr = {'Name': 'NAME1', 'Age': 'AGE1', 'Height': 'HEIGHT1'}
row_corr = {0: 'a', 1: 'b', 2: 'c'}

df.rename(index=row_corr, columns=col_corr, inplace=True)
df

   NAME1  AGE1 HEIGHT1
a   John  25.0   175.0
b  Miraj  None   162.0
c   None  30.0    None

In [62]:
# performing the query() function in the dataframe

# Create a sample DataFrame
data = {'Name': ['John', 'Emma', 'Michael', 'Sophia'],
'Age': [25, 28, 22, 30],
'Height': [175, 162, 180, 168]}
df = pd.DataFrame(data)
# Print the original DataFrame
print("Original DataFrame:")
print(df)
#...................................see from here....................................................................# Perform different types of queries
filtered_df1 = df.query("Age > 25 and Height < 170") # Numeric comparison
filtered_df2 = df.query("Name == 'John'") # Name column ma john vako row dinxa
filtered_df3 = df.query("Name in ['John', 'Emma']") # Select rows where Name is either 'John' or 'Emma'
filtered_df4 = df.query("not Height <= 168") # # Select rows where Height is not lesser equal to 168
filtered_df5 = df.query("Name.str.startswith('S')") # Select rows where Name starts with the letter 'M'
# Print the filtered DataFrame
print("\n")
print(filtered_df1)
print("\n")
print(filtered_df2)
print("\n")
print(filtered_df3)
print("\n")
print(filtered_df4)
print("\n")
print(filtered_df5)

Original DataFrame:
      Name  Age  Height
0     John   25     175
1     Emma   28     162
2  Michael   22     180
3   Sophia   30     168


     Name  Age  Height
1    Emma   28     162
3  Sophia   30     168


   Name  Age  Height
0  John   25     175


   Name  Age  Height
0  John   25     175
1  Emma   28     162


      Name  Age  Height
0     John   25     175
2  Michael   22     180


     Name  Age  Height
3  Sophia   30     168

In [78]:
# Create a sample DataFrame with missing values
data = {'Name': ['John', np.nan, 'Michael'],
'Age': [25, np.nan, 22],
'Height': [175, 162, np.nan]}
df = pd.DataFrame(data)
df

      Name   Age  Height
0     John  25.0   175.0
1      NaN   NaN   162.0
2  Michael  22.0     NaN

In [79]:
df['Name'].notna() # returns the boolean value true if there is value in dataframe

0     True
1    False
2     True
Name: Name, dtype: bool

In [83]:
df['Name'].isnull() # return true if there is null value

0    False
1     True
2    False
Name: Name, dtype: bool

In [84]:
# returns the row which have values
df[df['Name'].notna()]

      Name   Age  Height
0     John  25.0   175.0
2  Michael  22.0     NaN

In [85]:
# just creating a data frame
dict = {'name':['miraj','sabal','sarita','rashmi','sabnam'],
'roll':[1,2,3,4,5] ,'age':[13,34,32,54,32] }
df=pd.DataFrame(dict)
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [86]:
s = df.nsmallest(3, 'age') #age column ko 2 ota smallest value dinxa
s

     name  roll  age
0   miraj     1   13
2  sarita     3   32
4  sabnam     5   32

In [87]:
l=df.nlargest(2, 'age') #age column ko 2 ota largest value dinxa
l

     name  roll  age
3  rashmi     4   54
1   sabal     2   34

In [88]:
df # dataframe

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [89]:
df.info()
#This method provides a concise summary of a DataFrame, including its data types, non-null values, and memory

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   roll    5 non-null      int64
 2   age     5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

In [91]:
df

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [93]:
df.describe()
#This method generates descriptive statistics of a DataFrame,
#including count, mean, standard deviation, minimum, maximum, and quartile values.

           roll        age
count  5.000000   5.000000
mean   3.000000  33.000000
std    1.581139  14.525839
min    1.000000  13.000000
25%    2.000000  32.000000
50%    3.000000  32.000000
75%    4.000000  34.000000
max    5.000000  54.000000

In [94]:
df.count()
# count() returns the total no of non-null values in each column of a DataFrame or in the entire Series.

name    5
roll    5
age     5
dtype: int64

In [95]:
#copying the dataframe into m
m=df.copy()
m

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [96]:
df #original dataframe

     name  roll  age
0   miraj     1   13
1   sabal     2   34
2  sarita     3   32
3  rashmi     4   54
4  sabnam     5   32

In [97]:
#kati ota unique values each column ma tyo dinxa (duplicated values lai euta consider garxa)
df.nunique() #age ma 32 dui ota repeat vako xa tei vara eutai manera value diyo

name    5
roll    5
age     4
dtype: int64

# IMP Functions, Accessing values, Slicing in data frame

In [98]:
import pandas as pd
df=pd.read_excel(r"/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/example.xlsx")
df

              Name  Age  Roll  Salary            Address
0         John Doe   27   101   50000    123 Main Street
1       Jane Smith   32   102   65000     456 Elm Avenue
2    David Johnson   41   103   80000       789 Oak Lane
3   Sarah Williams   29   104   55000      321 Pine Road
4    Michael Brown   35   105   70000    654 Maple Drive
5      Emily Davis   24   106   45000   987 Cedar Street
6     James Wilson   38   107   75000    543 Birch Court
7  Jennifer Taylor   31   108   60000    876 Walnut Lane
8  Robert Anderson   26   109   48000  234 Spruce Avenue
9   Jessica Thomas   33   110   68000    567 Cherry Lane

In [99]:
# To set the custom index in data frame by reading excel and CSV File
df=pd.read_excel(r'/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/example.xlsx',index_col = 'Roll')
df

                 Name  Age  Salary            Address
Roll
101          John Doe   27   50000    123 Main Street
102        Jane Smith   32   65000     456 Elm Avenue
103     David Johnson   41   80000       789 Oak Lane
104    Sarah Williams   29   55000      321 Pine Road
105     Michael Brown   35   70000    654 Maple Drive
106       Emily Davis   24   45000   987 Cedar Street
107      James Wilson   38   75000    543 Birch Court
108   Jennifer Taylor   31   60000    876 Walnut Lane
109   Robert Anderson   26   48000  234 Spruce Avenue
110    Jessica Thomas   33   68000    567 Cherry Lane

In [100]:
df=pd.read_excel(r'/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/example.xlsx')
df.set_index("Name",inplace=True)

In [101]:
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [102]:
#we can also give index like this
df=pd.read_excel(r'/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/example.xlsx')
df.set_index("Name", inplace=True) #.set_index() returns new df so to modify in old data frame inplace=True
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [105]:
# To make data frame from the specific column while reading csv and excel file
df=pd.read_excel(r'/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/example.xlsx',index_col = 'Roll', usecols=['Name','Age','Roll'])
df

                 Name  Age
Roll
101          John Doe   27
102        Jane Smith   32
103     David Johnson   41
104    Sarah Williams   29
105     Michael Brown   35
106       Emily Davis   24
107      James Wilson   38
108   Jennifer Taylor   31
109   Robert Anderson   26
110    Jessica Thomas   33

In [106]:
# To get only specific rows in data frame (nrows)
df=pd.read_excel(r'/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/example.xlsx',index_col = 'Roll', usecols=['Name','Age','Roll'], nrows=2)
df

            Name  Age
Roll
101     John Doe   27
102   Jane Smith   32

In [107]:
df=pd.read_excel(r'/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/example.xlsx')
df

              Name  Age  Roll  Salary            Address
0         John Doe   27   101   50000    123 Main Street
1       Jane Smith   32   102   65000     456 Elm Avenue
2    David Johnson   41   103   80000       789 Oak Lane
3   Sarah Williams   29   104   55000      321 Pine Road
4    Michael Brown   35   105   70000    654 Maple Drive
5      Emily Davis   24   106   45000   987 Cedar Street
6     James Wilson   38   107   75000    543 Birch Court
7  Jennifer Taylor   31   108   60000    876 Walnut Lane
8  Robert Anderson   26   109   48000  234 Spruce Avenue
9   Jessica Thomas   33   110   68000    567 Cherry Lane

In [36]:
df.head() #gives first 5 rows

             Name  Age  Roll  Salary          Address
0        John Doe   27   101   50000  123 Main Street
1      Jane Smith   32   102   65000   456 Elm Avenue
2   David Johnson   41   103   80000     789 Oak Lane
3  Sarah Williams   29   104   55000    321 Pine Road
4   Michael Brown   35   105   70000  654 Maple Drive

In [109]:
df.tail() #gives last 5 rows
#we can also specify how much we want df.head(10), df.tail(11)

              Name  Age  Roll  Salary            Address
5      Emily Davis   24   106   45000   987 Cedar Street
6     James Wilson   38   107   75000    543 Birch Court
7  Jennifer Taylor   31   108   60000    876 Walnut Lane
8  Robert Anderson   26   109   48000  234 Spruce Avenue
9   Jessica Thomas   33   110   68000    567 Cherry Lane

In [110]:
df.sample(5)

             Name  Age  Roll  Salary           Address
1      Jane Smith   32   102   65000    456 Elm Avenue
5     Emily Davis   24   106   45000  987 Cedar Street
9  Jessica Thomas   33   110   68000   567 Cherry Lane
6    James Wilson   38   107   75000   543 Birch Court
4   Michael Brown   35   105   70000   654 Maple Drive

In [117]:
# to get particular colum form the dataframe
df['Name']

0           John Doe
1         Jane Smith
2      David Johnson
3     Sarah Williams
4      Michael Brown
5        Emily Davis
6       James Wilson
7    Jennifer Taylor
8    Robert Anderson
9     Jessica Thomas
Name: Name, dtype: object

In [113]:
# to get specific value from the colum of dataframe (data frame bata series aayo series bata index bata value)
df['Name'][5]

'Emily Davis'

In [114]:
# To get only 5 value from colums/series
df['Name'].head()

0          John Doe
1        Jane Smith
2     David Johnson
3    Sarah Williams
4     Michael Brown
Name: Name, dtype: object

In [118]:
#if we have to access the two colums form the data frame the we have to use use nexted list
df[["Name","Roll","Salary","Address"]]

              Name  Roll  Salary            Address
0         John Doe   101   50000    123 Main Street
1       Jane Smith   102   65000     456 Elm Avenue
2    David Johnson   103   80000       789 Oak Lane
3   Sarah Williams   104   55000      321 Pine Road
4    Michael Brown   105   70000    654 Maple Drive
5      Emily Davis   106   45000   987 Cedar Street
6     James Wilson   107   75000    543 Birch Court
7  Jennifer Taylor   108   60000    876 Walnut Lane
8  Robert Anderson   109   48000  234 Spruce Avenue
9   Jessica Thomas   110   68000    567 Cherry Lane

In [119]:
# slicing #default slicing is row
df[2:7]

             Name  Age  Roll  Salary           Address
2   David Johnson   41   103   80000      789 Oak Lane
3  Sarah Williams   29   104   55000     321 Pine Road
4   Michael Brown   35   105   70000   654 Maple Drive
5     Emily Davis   24   106   45000  987 Cedar Street
6    James Wilson   38   107   75000   543 Birch Court

In [120]:
# now getting colum from the slicing
df[2:7]['Salary']

2    80000
3    55000
4    70000
5    45000
6    75000
Name: Salary, dtype: int64

In [121]:
df[0:10:2] #with two step slicing

              Name  Age  Roll  Salary            Address
0         John Doe   27   101   50000    123 Main Street
2    David Johnson   41   103   80000       789 Oak Lane
4    Michael Brown   35   105   70000    654 Maple Drive
6     James Wilson   38   107   75000    543 Birch Court
8  Robert Anderson   26   109   48000  234 Spruce Avenue

In [123]:
# slicing multiple colums in dataframe
df[['Name','Age','Salary']][2:9]

              Name  Age  Salary
2    David Johnson   41   80000
3   Sarah Williams   29   55000
4    Michael Brown   35   70000
5      Emily Davis   24   45000
6     James Wilson   38   75000
7  Jennifer Taylor   31   60000
8  Robert Anderson   26   48000

In [124]:
df

              Name  Age  Roll  Salary            Address
0         John Doe   27   101   50000    123 Main Street
1       Jane Smith   32   102   65000     456 Elm Avenue
2    David Johnson   41   103   80000       789 Oak Lane
3   Sarah Williams   29   104   55000      321 Pine Road
4    Michael Brown   35   105   70000    654 Maple Drive
5      Emily Davis   24   106   45000   987 Cedar Street
6     James Wilson   38   107   75000    543 Birch Court
7  Jennifer Taylor   31   108   60000    876 Walnut Lane
8  Robert Anderson   26   109   48000  234 Spruce Avenue
9   Jessica Thomas   33   110   68000    567 Cherry Lane

In [125]:
# to get specific row as series
df.iloc[2] # gives index 2 row value as series

Name       David Johnson
Age                   41
Roll                 103
Salary             80000
Address     789 Oak Lane
Name: 2, dtype: object

In [128]:
df=pd.read_excel(r"/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/example.xlsx",index_col="Name")
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [129]:
# To get value of James Wilson row
df.iloc[6]

Age                     38
Roll                   107
Salary               75000
Address    543 Birch Court
Name: James Wilson, dtype: object

In [130]:
df.loc['James Wilson']

Age                     38
Roll                   107
Salary               75000
Address    543 Birch Court
Name: James Wilson, dtype: object

# Sorting the dataframe on the basis Values of column asscending and descending

In [131]:
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [132]:
#sorting Assending wise
df.sort_values('Salary')

                 Age  Roll  Salary            Address
Name
Emily Davis       24   106   45000   987 Cedar Street
Robert Anderson   26   109   48000  234 Spruce Avenue
John Doe          27   101   50000    123 Main Street
Sarah Williams    29   104   55000      321 Pine Road
Jennifer Taylor   31   108   60000    876 Walnut Lane
Jane Smith        32   102   65000     456 Elm Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane
Michael Brown     35   105   70000    654 Maple Drive
James Wilson      38   107   75000    543 Birch Court
David Johnson     41   103   80000       789 Oak Lane

In [133]:
#sorting Descending wise
df.sort_values('Salary', ascending=False)

                 Age  Roll  Salary            Address
Name
David Johnson     41   103   80000       789 Oak Lane
James Wilson      38   107   75000    543 Birch Court
Michael Brown     35   105   70000    654 Maple Drive
Jessica Thomas    33   110   68000    567 Cherry Lane
Jane Smith        32   102   65000     456 Elm Avenue
Jennifer Taylor   31   108   60000    876 Walnut Lane
Sarah Williams    29   104   55000      321 Pine Road
John Doe          27   101   50000    123 Main Street
Robert Anderson   26   109   48000  234 Spruce Avenue
Emily Davis       24   106   45000   987 Cedar Street

In [134]:
df['Roll'].sort_values(ascending=False)

Name
Jessica Thomas     110
Robert Anderson    109
Jennifer Taylor    108
James Wilson       107
Emily Davis        106
Michael Brown      105
Sarah Williams     104
David Johnson      103
Jane Smith         102
John Doe           101
Name: Roll, dtype: int64

# Adding and Dropping the Column in Data Frame

In [135]:
df=pd.read_excel(r"/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/example.xlsx")
df

              Name  Age  Roll  Salary            Address
0         John Doe   27   101   50000    123 Main Street
1       Jane Smith   32   102   65000     456 Elm Avenue
2    David Johnson   41   103   80000       789 Oak Lane
3   Sarah Williams   29   104   55000      321 Pine Road
4    Michael Brown   35   105   70000    654 Maple Drive
5      Emily Davis   24   106   45000   987 Cedar Street
6     James Wilson   38   107   75000    543 Birch Court
7  Jennifer Taylor   31   108   60000    876 Walnut Lane
8  Robert Anderson   26   109   48000  234 Spruce Avenue
9   Jessica Thomas   33   110   68000    567 Cherry Lane

In [136]:
# Adding new Column Gender
df['Gender']=['m','f','f','m','m','f','m','f','m','f']
df

              Name  Age  Roll  Salary            Address Gender
0         John Doe   27   101   50000    123 Main Street      m
1       Jane Smith   32   102   65000     456 Elm Avenue      f
2    David Johnson   41   103   80000       789 Oak Lane      f
3   Sarah Williams   29   104   55000      321 Pine Road      m
4    Michael Brown   35   105   70000    654 Maple Drive      m
5      Emily Davis   24   106   45000   987 Cedar Street      f
6     James Wilson   38   107   75000    543 Birch Court      m
7  Jennifer Taylor   31   108   60000    876 Walnut Lane      f
8  Robert Anderson   26   109   48000  234 Spruce Avenue      m
9   Jessica Thomas   33   110   68000    567 Cherry Lane      f

In [138]:
df['roll+Age']=df['Age']+df['Roll'] # 2 ota series return hunxa ra sum hunxa ani naya column ma basnxa value
df

              Name  Age  Roll  Salary            Address Gender  roll+Age
0         John Doe   27   101   50000    123 Main Street      m       128
1       Jane Smith   32   102   65000     456 Elm Avenue      f       134
2    David Johnson   41   103   80000       789 Oak Lane      f       144
3   Sarah Williams   29   104   55000      321 Pine Road      m       133
4    Michael Brown   35   105   70000    654 Maple Drive      m       140
5      Emily Davis   24   106   45000   987 Cedar Street      f       130
6     James Wilson   38   107   75000    543 Birch Court      m       145
7  Jennifer Taylor   31   108   60000    876 Walnut Lane      f       139
8  Robert Anderson   26   109   48000  234 Spruce Avenue      m       135
9   Jessica Thomas   33   110   68000    567 Cherry Lane      f       143

In [86]:
df=df.drop(columns="roll+Age") # does not delete on orignal datafrae so df=....
df

              Name  Age  Roll  Salary            Address Gender
0         John Doe   27   101   50000    123 Main Street      m
1       Jane Smith   32   102   65000     456 Elm Avenue      f
2    David Johnson   41   103   80000       789 Oak Lane      f
3   Sarah Williams   29   104   55000      321 Pine Road      m
4    Michael Brown   35   105   70000    654 Maple Drive      m
5      Emily Davis   24   106   45000   987 Cedar Street      f
6     James Wilson   38   107   75000    543 Birch Court      m
7  Jennifer Taylor   31   108   60000    876 Walnut Lane      f
8  Robert Anderson   26   109   48000  234 Spruce Avenue      m
9   Jessica Thomas   33   110   68000    567 Cherry Lane      f

In [139]:
#Adding multiple Colums in data frame
df[['Height', 'Weight']] = [['5ft', '1kg'],
['5.5ft', '2kg'],
['6ft', '33kg'],
['7ft', '43kg'],
['4ft', '34kg'],
['4ft', '56kg'],
['3ft', '45kg'],
['5ft', '76kg'],
['4.5ft', '78kg'],
['6ft', '90kg']]
df

,Name,Age,Roll,Salary,Address,Gender,roll+Age,Height,Weight
0,John Doe,27,101,50000,123 Main Street,m,128,5ft,1kg
1,Jane Smith,32,102,65000,456 Elm Avenue,f,134,5.5ft,2kg
2,David Johnson,41,103,80000,789 Oak Lane,f,144,6ft,33kg
3,Sarah Williams,29,104,55000,321 Pine Road,m,133,7ft,43kg
4,Michael Brown,35,105,70000,654 Maple Drive,m,140,4ft,34kg
5,Emily Davis,24,106,45000,987 Cedar Street,f,130,4ft,56kg
6,James Wilson,38,107,75000,543 Birch Court,m,145,3ft,45kg
7,Jennifer Taylor,31,108,60000,876 Walnut Lane,f,139,5ft,76kg
8,Robert Anderson,26,109,48000,234 Spruce Avenue,m,135,4.5ft,78kg
9,Jessica Thomas,33,110,68000,567 Cherry Lane,f,143,6ft,90kg

In [140]:
# droppimg multiple columns in dataframe
df=df.drop(columns=['Height','Weight','Gender'])
df

              Name  Age  Roll  Salary            Address  roll+Age
0         John Doe   27   101   50000    123 Main Street       128
1       Jane Smith   32   102   65000     456 Elm Avenue       134
2    David Johnson   41   103   80000       789 Oak Lane       144
3   Sarah Williams   29   104   55000      321 Pine Road       133
4    Michael Brown   35   105   70000    654 Maple Drive       140
5      Emily Davis   24   106   45000   987 Cedar Street       130
6     James Wilson   38   107   75000    543 Birch Court       145
7  Jennifer Taylor   31   108   60000    876 Walnut Lane       139
8  Robert Anderson   26   109   48000  234 Spruce Avenue       135
9   Jessica Thomas   33   110   68000    567 Cherry Lane       143

# Exporting the DataFrame into Excel, csv and txt file

In [141]:
import pandas as pd
dict={'name':['miraj','ram','shyam','gita'],'roll':[1,2,3,4],'age':[12,32,31,54]}
df=pd.DataFrame(dict)
df

    name  roll  age
0  miraj     1   12
1    ram     2   32
2  shyam     3   31
3   gita     4   54

In [142]:
# Expoting the data frame into excel file
df.to_excel("export_into_excel.xlsx",index=False)

In [109]:
# Expoting the data frame into csv file
df.to_csv("export_into_csv.csv",index=False)

In [143]:
# Expoting the data frame into txt file
df.to_csv("export_into_txt.txt",index=False)

# Understanding loc and iloc

In [145]:
df=pd.read_excel(r'/kaggle/input/datasets/mirajverisk/pandas-datas/pandas_data/example.xlsx', index_col="Name")
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

# Data Selection using `loc` and `iloc`

- **`loc`** – Retrieves data based on **labels** (row and column names).

  ```python
  df.loc[1:3, 'name':'roll']
  ```

  - Label-based indexing.
  - The stop value is **inclusive** in slicing.
  - Includes rows `1` to `3` and columns from `'name'` to `'roll'`.

- **`iloc`** – Retrieves data based on **integer positions (indices)**.

  ```python
  df.iloc[1:4, 0:2]
  ```

  - Index-based indexing.
  - The stop value is **exclusive** in slicing.
  - Includes rows `1` to `3` and columns `0` to `1`.

In [146]:
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [147]:
#using loc for row df.loc[row,column]
df.loc['John Doe']

Age                     27
Roll                   101
Salary               50000
Address    123 Main Street
Name: John Doe, dtype: object

In [150]:
#using loc to get value
print(df.loc['John Doe','Salary']) #df.loc[row,column]

50000

In [151]:
#multiple column chaiye list bhitra halne
df.loc['John Doe',['Salary','Address']] #df.loc[row,column]

Salary               50000
Address    123 Main Street
Name: John Doe, dtype: object

In [152]:
# slicing row
df.loc['John Doe':'Michael Brown']

                Age  Roll  Salary          Address
Name
John Doe         27   101   50000  123 Main Street
Jane Smith       32   102   65000   456 Elm Avenue
David Johnson    41   103   80000     789 Oak Lane
Sarah Williams   29   104   55000    321 Pine Road
Michael Brown    35   105   70000  654 Maple Drive

In [154]:
df.iloc[0:5]

                Age  Roll  Salary          Address
Name
John Doe         27   101   50000  123 Main Street
Jane Smith       32   102   65000   456 Elm Avenue
David Johnson    41   103   80000     789 Oak Lane
Sarah Williams   29   104   55000    321 Pine Road
Michael Brown    35   105   70000  654 Maple Drive

In [155]:
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [156]:
# getting multiple values from the dataframe using loc
df.loc['Jane Smith':'David Johnson',["Age","Roll"]]

               Age  Roll
Name
Jane Smith      32   102
David Johnson   41   103

In [157]:
# getting multiple values from the dataframe using loc
df.loc['Jane Smith':'David Johnson','Age':'Roll']

               Age  Roll
Name
Jane Smith      32   102
David Johnson   41   103

In [158]:
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [159]:
#jane dekhi david samma ko age ra address matra chaiye
df.loc['Jane Smith':'David Johnson',['Age','Address']]

               Age         Address
Name
Jane Smith      32  456 Elm Avenue
David Johnson   41    789 Oak Lane

In [160]:
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [163]:
# 104 ra 105 matra chaiyo rey aba
df.loc[['Sarah Williams','Michael Brown'],'Roll']

Name
Sarah Williams    104
Michael Brown     105
Name: Roll, dtype: int64

In [164]:
df

                 Age  Roll  Salary            Address
Name
John Doe          27   101   50000    123 Main Street
Jane Smith        32   102   65000     456 Elm Avenue
David Johnson     41   103   80000       789 Oak Lane
Sarah Williams    29   104   55000      321 Pine Road
Michael Brown     35   105   70000    654 Maple Drive
Emily Davis       24   106   45000   987 Cedar Street
James Wilson      38   107   75000    543 Birch Court
Jennifer Taylor   31   108   60000    876 Walnut Lane
Robert Anderson   26   109   48000  234 Spruce Avenue
Jessica Thomas    33   110   68000    567 Cherry Lane

In [166]:
df.iloc[3:5,1]

Name
Sarah Williams    104
Michael Brown     105
Name: Roll, dtype: int64

In [169]:
#we can convert any row or column into list
list(df['Roll'])

[101, 102, 103, 104, 105, 106, 107, 108, 109, 110]

In [170]:
list(df.loc['John Doe'])

[np.int64(27), np.int64(101), np.int64(50000), '123 Main Street']

# Handeling missing data in data frame

In [171]:
df = pd.DataFrame({
    'SN': [1.0, 2.0, 3.0, 4.0, np.nan, 6.0],
    'Age': [32, 5, 42, 37, 29, 31],
    'Roll': ['A01', 'B07', 'C03', np.nan, 'E05', 'F08'],
    'Employee ID': [100234.0, 102345.0, 105678.0, 107890.0, 109876.0, np.nan],
    'Name': [np.nan, 'Jane Smith', 'David Brown', 'Lisa Green', 'Mark Davis', 'Anna']
})

df

    SN  Age Roll  Employee ID         Name
0  1.0   32  A01     100234.0          NaN
1  2.0    5  B07     102345.0   Jane Smith
2  3.0   42  C03     105678.0  David Brown
3  4.0   37  NaN     107890.0   Lisa Green
4  NaN   29  E05     109876.0   Mark Davis
5  6.0   31  F08          NaN         Anna

In [172]:
#check if the values are null
df.isnull()

      SN    Age   Roll  Employee ID   Name
0  False  False  False        False   True
1  False  False  False        False  False
2  False  False  False        False  False
3  False  False   True        False  False
4   True  False  False        False  False
5  False  False  False         True  False

In [173]:
# returns the total number of null fields in each columns
df.isnull().sum()

SN             1
Age            0
Roll           1
Employee ID    1
Name           1
dtype: int64

# TO DELETE THE VALUES ROW

In [176]:
df = pd.DataFrame({
    'SN': [1.0, 2.0, 3.0, 4.0, np.nan, 6.0],
    'Age': [32, 5, 42, 37, 29, 31],
    'Roll': ['A01', 'B07', 'C03', np.nan, 'E05', 'F08'],
    'Employee ID': [100234.0, 102345.0, 105678.0, 107890.0, 109876.0, np.nan],
    'Name': [np.nan, 'Jane Smith', 'David Brown', 'Lisa Green', 'Mark Davis', 'Anna']
})

df

    SN  Age Roll  Employee ID         Name
0  1.0   32  A01     100234.0          NaN
1  2.0    5  B07     102345.0   Jane Smith
2  3.0   42  C03     105678.0  David Brown
3  4.0   37  NaN     107890.0   Lisa Green
4  NaN   29  E05     109876.0   Mark Davis
5  6.0   31  F08          NaN         Anna

In [179]:
#to delete the row which have no value
df.dropna(inplace=True) #inplace true is for to change in original data frame
df

    SN  Age Roll  Employee ID         Name
1  2.0    5  B07     102345.0   Jane Smith
2  3.0   42  C03     105678.0  David Brown

In [180]:
# we can also remove the missing values from specific colums
df['Name'].dropna() # 0 index NAN is removed

1     Jane Smith
2    David Brown
Name: Name, dtype: object

In [181]:
df[['Name','Roll']].dropna() # removing the NAN values from from the name ans roll column

          Name Roll
1   Jane Smith  B07
2  David Brown  C03

# TO FILL THE MISSING VALUE FIELD WITH DEFAULT VALUE OR OTHER VALUES

In [183]:
df = pd.DataFrame({
    'SN': [1.0, 2.0, 3.0, 4.0, np.nan, 6.0],
    'Age': [32, 5, 42, 37, 29, 31],
    'Roll': ['A01', 'B07', 'C03', np.nan, 'E05', 'F08'],
    'Employee ID': [100234.0, 102345.0, 105678.0, 107890.0, 109876.0, np.nan],
    'Name': [np.nan, 'Jane Smith', 'David Brown', 'Lisa Green', 'Mark Davis', 'Anna']
})

df

    SN  Age Roll  Employee ID         Name
0  1.0   32  A01     100234.0          NaN
1  2.0    5  B07     102345.0   Jane Smith
2  3.0   42  C03     105678.0  David Brown
3  4.0   37  NaN     107890.0   Lisa Green
4  NaN   29  E05     109876.0   Mark Davis
5  6.0   31  F08          NaN         Anna

In [189]:
#filling all the missing filelds with 4
df.fillna(4)

    SN  Age Roll  Employee ID         Name
0  1.0   32  A01     100234.0            4
1  2.0    5  B07     102345.0   Jane Smith
2  3.0   42  C03     105678.0  David Brown
3  4.0   37    4     107890.0   Lisa Green
4  4.0   29  E05     109876.0   Mark Davis
5  6.0   31  F08          4.0         Anna

In [190]:
#filling a specific column with valuie
df

    SN  Age Roll  Employee ID         Name
0  1.0   32  A01     100234.0          NaN
1  2.0    5  B07     102345.0   Jane Smith
2  3.0   42  C03     105678.0  David Brown
3  4.0   37  NaN     107890.0   Lisa Green
4  NaN   29  E05     109876.0   Mark Davis
5  6.0   31  F08          NaN         Anna

In [130]:
df.fillna({'Name': 'miraj'}, inplace=True)

In [192]:
df

    SN  Age Roll  Employee ID         Name
0  1.0   32  A01     100234.0          NaN
1  2.0    5  B07     102345.0   Jane Smith
2  3.0   42  C03     105678.0  David Brown
3  4.0   37  NaN     107890.0   Lisa Green
4  NaN   29  E05     109876.0   Mark Davis
5  6.0   31  F08          NaN         Anna

In [193]:
# we can also give mean vaue to empty field like this
df['SN'].fillna(df['SN'].mean()) #SN KO MEAN NIKALERA FILLNA MA AS A ARGUMENT VALUE PASS GARDINXA

0    1.0
1    2.0
2    3.0
3    4.0
4    3.2
5    6.0
Name: SN, dtype: float64

# Handeling the duplicated Values

In [194]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'SN': [1, 2, 3, 4, 2, 6, 4],
    'Age': [32, 5, 42, 34, 5, 31, 34],
    'Roll': ['A01', 'B07', 'C03', 'df4', 'B07', 'F08', 'df4'],
    'Employee ID': [100234.0, 102345.0, 105678.0, 23242.0, 102345.0, np.nan, 23242.0],
    'Name': ['mmd', 'Jane Smith', 'David Brown', 'miraj', 'Jane Smith', 'Anna', 'miraj']
})

df

   SN  Age Roll  Employee ID         Name
0   1   32  A01     100234.0          mmd
1   2    5  B07     102345.0   Jane Smith
2   3   42  C03     105678.0  David Brown
3   4   34  df4      23242.0        miraj
4   2    5  B07     102345.0   Jane Smith
5   6   31  F08          NaN         Anna
6   4   34  df4      23242.0        miraj

In [200]:
# to check the values are duplicated or not in data frame
df.duplicated()

0    False
1    False
2    False
3    False
5    False
dtype: bool

In [201]:
# to see the actual duplicated value / we wrap with another df[] only true values comes
df[df.duplicated()]

Empty DataFrame
Columns: [SN, Age, Roll, Employee ID, Name]
Index: []

In [202]:
#to remove the duplicated values we can use
df.drop_duplicates(inplace=True)
df

   SN  Age Roll  Employee ID         Name
0   1   32  A01     100234.0          mmd
1   2    5  B07     102345.0   Jane Smith
2   3   42  C03     105678.0  David Brown
3   4   34  df4      23242.0        miraj
5   6   31  F08          NaN         Anna

In [203]:
df # dataframe

   SN  Age Roll  Employee ID         Name
0   1   32  A01     100234.0          mmd
1   2    5  B07     102345.0   Jane Smith
2   3   42  C03     105678.0  David Brown
3   4   34  df4      23242.0        miraj
5   6   31  F08          NaN         Anna

In [199]:
# to see the non repeated value we can use not(~)
~df.duplicated()

0    True
1    True
2    True
3    True
5    True
dtype: bool

# TO CHECK the number of unique values in each column

In [204]:
df

   SN  Age Roll  Employee ID         Name
0   1   32  A01     100234.0          mmd
1   2    5  B07     102345.0   Jane Smith
2   3   42  C03     105678.0  David Brown
3   4   34  df4      23242.0        miraj
5   6   31  F08          NaN         Anna

In [205]:
df.nunique() # sabai column ma kati ota unique value xa teko count dinxa

SN             5
Age            5
Roll           5
Employee ID    4
Name           5
dtype: int64

# Checking conditions in to filter data

In [206]:
df

   SN  Age Roll  Employee ID         Name
0   1   32  A01     100234.0          mmd
1   2    5  B07     102345.0   Jane Smith
2   3   42  C03     105678.0  David Brown
3   4   34  df4      23242.0        miraj
5   6   31  F08          NaN         Anna

In [208]:
#Checking if Name colum have miraj or not
df['Name']=='miraj'

0    False
1    False
2    False
3     True
5    False
Name: Name, dtype: bool

In [144]:
# to extract the value of row of miraj
df[df['Name']=='miraj']

   SN  Age Roll  Employee ID   Name
3   4   34  df4      23242.0  miraj

In [209]:
#To check multiple conditions
df[(df['Age'] == 31) & (df['SN']>5)]

   SN  Age Roll  Employee ID  Name
5   6   31  F08          NaN  Anna

# DELETE SPECIFIC ROW AND COLUMN

In [210]:
df

   SN  Age Roll  Employee ID         Name
0   1   32  A01     100234.0          mmd
1   2    5  B07     102345.0   Jane Smith
2   3   42  C03     105678.0  David Brown
3   4   34  df4      23242.0        miraj
5   6   31  F08          NaN         Anna

In [211]:
df.index=['1st','2nd','3rd','4th','5th']
df

     SN  Age Roll  Employee ID         Name
1st   1   32  A01     100234.0          mmd
2nd   2    5  B07     102345.0   Jane Smith
3rd   3   42  C03     105678.0  David Brown
4th   4   34  df4      23242.0        miraj
5th   6   31  F08          NaN         Anna

In [212]:
#To delete the specific row
df.drop(labels='1st') # miraj vako row hatyo

     SN  Age Roll  Employee ID         Name
2nd   2    5  B07     102345.0   Jane Smith
3rd   3   42  C03     105678.0  David Brown
4th   4   34  df4      23242.0        miraj
5th   6   31  F08          NaN         Anna

In [213]:
#To delete the multiple specific row
df.drop(labels=['1st','4th'])

     SN  Age Roll  Employee ID         Name
2nd   2    5  B07     102345.0   Jane Smith
3rd   3   42  C03     105678.0  David Brown
5th   6   31  F08          NaN         Anna

In [214]:
df

     SN  Age Roll  Employee ID         Name
1st   1   32  A01     100234.0          mmd
2nd   2    5  B07     102345.0   Jane Smith
3rd   3   42  C03     105678.0  David Brown
4th   4   34  df4      23242.0        miraj
5th   6   31  F08          NaN         Anna

In [215]:
#To delete the specific column
df.drop(columns='Name')

     SN  Age Roll  Employee ID
1st   1   32  A01     100234.0
2nd   2    5  B07     102345.0
3rd   3   42  C03     105678.0
4th   4   34  df4      23242.0
5th   6   31  F08          NaN

In [216]:
df

     SN  Age Roll  Employee ID         Name
1st   1   32  A01     100234.0          mmd
2nd   2    5  B07     102345.0   Jane Smith
3rd   3   42  C03     105678.0  David Brown
4th   4   34  df4      23242.0        miraj
5th   6   31  F08          NaN         Anna

In [217]:
#To delete the specific column or row by another axis methhos ( 0---> row 1-----> column)
#deleting column
df.drop('Age', axis=1)

     SN Roll  Employee ID         Name
1st   1  A01     100234.0          mmd
2nd   2  B07     102345.0   Jane Smith
3rd   3  C03     105678.0  David Brown
4th   4  df4      23242.0        miraj
5th   6  F08          NaN         Anna

In [218]:
df

     SN  Age Roll  Employee ID         Name
1st   1   32  A01     100234.0          mmd
2nd   2    5  B07     102345.0   Jane Smith
3rd   3   42  C03     105678.0  David Brown
4th   4   34  df4      23242.0        miraj
5th   6   31  F08          NaN         Anna

In [220]:
#deleting row
df.drop('4th', axis=0)

     SN  Age Roll  Employee ID         Name
1st   1   32  A01     100234.0          mmd
2nd   2    5  B07     102345.0   Jane Smith
3rd   3   42  C03     105678.0  David Brown
5th   6   31  F08          NaN         Anna

In [221]:
df.drop(columns=['Age','Employee ID','Name'], inplace=True)
df

     SN Roll
1st   1  A01
2nd   2  B07
3rd   3  C03
4th   4  df4
5th   6  F08

# To concat dataframes

In [222]:
df1=pd.DataFrame({'Name':['miraj','aman'],'Roll':[10,11]})
df2=pd.DataFrame({'Name':['arbit','amir'],'Roll':[15,13]})
df3=pd.DataFrame({'Name':['june','july'],'Roll':[18,21]})
df=pd.concat([df1,df2,df3])
df

    Name  Roll
0  miraj    10
1   aman    11
0  arbit    15
1   amir    13
0   june    18
1   july    21

In [223]:
df=pd.concat([df1,df2,df3],keys=['group1','group2','group3'],names=['group','rowno'])
df

               Name  Roll
group  rowno
group1 0      miraj    10
       1       aman    11
group2 0      arbit    15
       1       amir    13
group3 0       june    18
       1       july    21

In [224]:
df=pd.concat([df1,df2,df3],keys=['group1','group2','group3'],names=['group','rowno']).reset_index()
df

    group  rowno   Name  Roll
0  group1      0  miraj    10
1  group1      1   aman    11
2  group2      0  arbit    15
3  group2      1   amir    13
4  group3      0   june    18
5  group3      1   july    21

# String Operation in the dataframe

In [225]:
import pandas as pd
# Create a sample DataFrame
df = pd.DataFrame({'name': ['John', 'Alice', 'Bob'],
'salary': ['10,000', '5,500', '8,750']})
# Remove commas from 'salary' column
#data frame ko sab element ko comma hatxa

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   salary  3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes

In [161]:
df

    name  salary
0   John  10,000
1  Alice   5,500
2    Bob   8,750

In [226]:
df['salary']= df['salary'].str.replace(',', '')

In [227]:

df

    name salary
0   John  10000
1  Alice   5500
2    Bob   8750